import static spark.Spark.staticFileLocation;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import spark.ModelAndView;
import spark.template.velocity.VelocityTemplateEngine;

import static spark.Spark.*;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        staticFileLocation("/public");
        String layout = "templates/layout.vtl";

        ProcessBuilder process = new ProcessBuilder();
        Integer port;
        if (process.environment().get("PORT") != null) {
            port = Integer.parseInt(process.environment().get("PORT"));
        } else {
            port = 4567;
        }

        port(port);

//        get("/", (request, response) -> {
//            Map<String, Object> model = new HashMap<String, Object>();
////            ArrayList<Task> todos = Task.;
////            model.put("mytodos", todos);
//            model.put("template", "templates/index.vtl");
//            return new ModelAndView(model, layout);
//        }, new VelocityTemplateEngine());

        get("/addTodoForm", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            model.put("categories", Category.all());
            model.put("template", "templates/addTodo.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

            //post: process new post form
        post("/addform", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();

                Integer i = Integer.parseInt(request.queryParams("categoryId"));
                Category category = Category.find(i);
                String description = request.queryParams("todoItem");
                Task newTask = new Task(description, category.getId());
                newTask.save();
                model.put("category", category);
                model.put("template", "templates/success.vtl");

            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        //add a new category
        post("/categories", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            String name = request.queryParams("name");
            Category newCategory = new Category(name);
            newCategory.save();
            model.put("template", "templates/success.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        //get category form
        get("/categories/new", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            model.put("template", "templates/category-form.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        //get all category
        get("/", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            model.put("categories", Category.all());
            model.put("template", "templates/index.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

        //get category by id
        get("/categories/:id", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            Category category = Category.find(Integer.parseInt(request.params(":id")));
            model.put("category", category);
            model.put("template", "templates/category.vtl");
            return new ModelAndView(model, layout);
        }, new VelocityTemplateEngine());

    }
}
